### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by fmoraless** [fmoraless/sistema#1]
```
PS C:\xampp\htdocs\sistema> npm install
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\copy-descriptor
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\class-utils
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\object-copy
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\stable
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\stackframe
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\error-stack-parser
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\stat-mode
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\statuses
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\http-errors
npm WARN checkPermissions Missing write access to C:\xampp\htdocs\sistema\node_modules\serve-index
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm ERR! path C:\xampp\htdocs\sistema\node_modules\copy-descriptor
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'C:\xampp\htdocs\sistema\node_modules\copy-descriptor'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francisco\AppData\Roaming\npm-cache\_logs\2018-05-27T05_00_09_616Z-debug.log
PS C:\xampp\htdocs\sistema> npm run dev
> @ dev C:\xampp\htdocs\sistema
> npm run development
> @ development C:\xampp\htdocs\sistema
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
"cross-env" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francisco\AppData\Roaming\npm-cache\_logs\2018-05-27T05_01_09_990Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francisco\AppData\Roaming\npm-cache\_logs\2018-05-27T05_01_10_136Z-debug.log
PS C:\xampp\htdocs\sistema>
```

**Comment by fmoraless** [comment]
[SOLUCIONADO]
Lo solucioné con lo siguiente:
Step 1: npm cache clean --force

Step 2: delete node_modules folder

Step 3: npm install

Con esto ya pude correr npm run dev y me compiló

 DONE  Compiled successfully in 114ms                                                                                                                 23:27:36                                            23:27:36
    As                                                                                          Asset    Size  Chunks             Chunk Names
\css\plantilla.css  302 kB          [emitted]
  \js\plantilla.js  334 kB          [emitted]
PS C:\xampp\htdocs\sistema>

**Comment by JuanOtavaloMaigua** [comment]
> 
> 
> [SOLUCIONADO]
> Lo solucioné con lo siguiente:
> Step 1: npm cache clean --force
> 
> Step 2: delete node_modules folder
> 
> Step 3: npm install
> 
> Con esto ya pude correr npm run dev y me compiló
> 
> DONE Compiled successfully in 114ms 23:27:36 23:27:36
> As Asset Size Chunks Chunk Names
> \css\plantilla.css 302 kB [emitted]
> \js\plantilla.js 334 kB [emitted]
> PS C:\xampp\htdocs\sistema>

Yo tenia un problema similar y logré solucionarlo con la solucion que dio.

**Comment by LumDev86** [comment]
Hola Yo tengo un problema no se es el mismo problema...
------------------------------------------------------------------
C:\Users\lucas\OneDrive\Escritorio\Proyectos React>npx create-react-app mi-app
"CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\lucas\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\lucas\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\lucas\AppData\Local\npm-cache\_logs\2024-01-12T18_08_17_448Z-debug-0.log

C:\Users\lucas\OneDrive\Escritorio\Proyectos React>

no le encuentro la solucion...
